# Generated by Django 5.0.2 on 2024-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uaccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
